spring:
  batch:
    job:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
  liquibase:
    change-log: classpath:liquibase/main.xml
    contexts: prod

  data:
    mongodb:
      database: library
      host: localhost
      port: 0
  main:
    allow-circular-references: true
  mongodb:
    embedded:
      version: 3.4.0

logging:
  level:
    ROOT: INFO
