version: "3"

services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    image: belovdp/library
    container_name: library
    restart: always
    privileged: true
    depends_on:
      - library-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://library-db:5432/library
      SPRING_DATASOURCE_USERNAME: library
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8099"

  library-db:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: password